# generated by datamodel-codegen:
#   filename:  https://analytics.gw.skaix-stg.engine.simon-kucher.com/openapi.json
#   timestamp: 2026-03-02T04:41:42+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, ConfigDict, Field, RootModel
from schemas.base import CamelCaseModel


class AssortmentItem(CamelCaseModel):
    sku_id: Annotated[str, Field(title="Sku Id")]
    brand: Annotated[str, Field(title="Brand")]
    own_brand: Annotated[bool, Field(title="Own Brand")] = False
    retailer: Annotated[str, Field(title="Retailer")]
    acv: Annotated[float, Field(title="Acv")]
    dollar_sales: Annotated[float, Field(title="Dollar Sales")]
    distribution_pct: Annotated[float, Field(title="Distribution Pct")]


class AssortmentResponse(CamelCaseModel):
    data: Annotated[list[AssortmentItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class BaselineMetrics(CamelCaseModel):
    avg_weekly_units: Annotated[float, Field(title="Avg Weekly Units")]
    avg_weekly_sales: Annotated[float, Field(title="Avg Weekly Sales")]
    avg_price: Annotated[float, Field(title="Avg Price")]
    non_promo_price: Annotated[float | None, Field(title="Non Promo Price")]


class BucketEffect(CamelCaseModel):
    coefficient: Annotated[float, Field(title="Coefficient")]
    lift_pct: Annotated[float, Field(title="Lift Pct")]
    std_error: Annotated[float | None, Field(title="Std Error")] = None
    p_value: Annotated[float | None, Field(title="P Value")] = None


class CDTAttrRank(CamelCaseModel):
    attribute: Annotated[str, Field(title="Attribute")]
    score: Annotated[float | None, Field(title="Score")] = None
    reason: Annotated[str | None, Field(title="Reason")] = None


class CDTNode(CamelCaseModel):
    id: Annotated[str, Field(title="Id")]
    depth: Annotated[int, Field(title="Depth")]
    sales: Annotated[float, Field(title="Sales")]
    growth_l12_t12: Annotated[float | None, Field(title="Growth L12 T12")] = None
    leaf: Annotated[bool, Field(title="Leaf")]
    split_attr: Annotated[str | None, Field(title="Split Attr")] = None
    score: Annotated[float | None, Field(title="Score")] = None
    value: Annotated[str | None, Field(title="Value")] = None
    sales_share: Annotated[float | None, Field(title="Sales Share")] = None
    children: Annotated[list[CDTNode] | None, Field(title="Children")] = None


class CDTNodeFlat(CamelCaseModel):
    id: Annotated[str, Field(title="Id")]
    depth: Annotated[int, Field(title="Depth")]
    sales: Annotated[float, Field(title="Sales")]
    growth_l12_t12: Annotated[float | None, Field(title="Growth L12 T12")] = None
    leaf: Annotated[bool, Field(title="Leaf")]
    split_attr: Annotated[str | None, Field(title="Split Attr")] = None
    score: Annotated[float | None, Field(title="Score")] = None
    value: Annotated[str | None, Field(title="Value")] = None
    sales_share: Annotated[float | None, Field(title="Sales Share")] = None


class CDTParams(CamelCaseModel):
    volume_col: Annotated[str, Field(title="Volume Col")] = "volume"
    min_group_share: Annotated[float, Field(title="Min Group Share")] = 0.05
    min_weeks: Annotated[int, Field(title="Min Weeks")] = 40
    time_decay_half_life: Annotated[
        float | None, Field(title="Time Decay Half Life")
    ] = None


class CDTRequest(CamelCaseModel):
    retailer: Annotated[str | None, Field(title="Retailer")] = None
    category: Annotated[str | None, Field(title="Category")] = None
    attributes: Annotated[list[str], Field(title="Attributes")] = [
        "brand",
        "pack_size_range",
        "price_tier",
    ]
    max_depth: Annotated[int, Field(ge=1, le=5, title="Max Depth")] = 3
    min_gain: Annotated[float, Field(title="Min Gain")] = 0.05
    params: CDTParams | None = None


class CDTSummary(CamelCaseModel):
    total_sales: Annotated[float, Field(title="Total Sales")]
    total_nodes: Annotated[int, Field(title="Total Nodes")]
    max_depth_reached: Annotated[int, Field(title="Max Depth Reached")]
    top_split_attribute: Annotated[str | None, Field(title="Top Split Attribute")] = (
        None
    )


class Summary(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")]


class CategoryInnovationRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    start_date: Annotated[
        date | None, Field(description="Analysis period start", title="Start Date")
    ] = None
    end_date: Annotated[
        date | None, Field(description="Analysis period end", title="End Date")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None


class ChannelLegend(Enum):
    brand = "brand"
    subcategory = "subcategory"
    category = "category"
    sku = "sku"
    manufacturer = "manufacturer"
    retailer = "retailer"
    channel = "channel"
    pack_size = "pack_size"
    price_tier = "price_tier"


class ChartType(Enum):
    bar = "bar"
    stacked_bar = "stacked_bar"
    grouped_bar = "grouped_bar"
    grouped = "grouped"
    pie = "pie"
    line = "line"
    table = "table"


class ConfigResponse(CamelCaseModel):
    tenant_id: Annotated[int | None, Field(title="Tenant Id")]
    category: Annotated[str, Field(title="Category")]
    config: Annotated[dict[str, Any], Field(title="Config")]


class CustomerPriceVariance(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    customer_id: Annotated[str, Field(title="Customer Id")]
    customer_name: Annotated[str, Field(title="Customer Name")]
    price: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Price")
    ]
    variance_pct: Annotated[
        str,
        Field(
            description="Variance from avg %",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Variance Pct",
        ),
    ]


class DataRange(CamelCaseModel):
    min_date: Annotated[date | None, Field(title="Min Date")] = None
    max_date: Annotated[date | None, Field(title="Max Date")] = None


class DepthRecommendation(CamelCaseModel):
    decile: Annotated[str, Field(title="Decile")]
    avg_roi: Annotated[float | None, Field(title="Avg Roi")]
    avg_uplift: Annotated[float | None, Field(title="Avg Uplift")]
    event_count: Annotated[int, Field(title="Event Count")]


class DownloadFormat(RootModel[Literal["xlsx"]]):
    root: Annotated[Literal["xlsx"], Field(title="DownloadFormat")]


class DownloadRequest(CamelCaseModel):
    format: Annotated[
        DownloadFormat, Field(default_factory=lambda: DownloadFormat("xlsx"))
    ]
    sheets: Annotated[
        dict[str, list[dict[str, Any]]],
        Field(
            description="Sheet name -> list of row objects",
            examples=[{"Dollar Share": [{"brand": "A", "share": 45.2}]}],
            title="Sheets",
        ),
    ]
    """
    Example: {'Dollar Share': [{'brand': 'A', 'share': 45.2}]}
    """


class DriverType(Enum):
    display = "display"
    feature = "feature"
    price_cut = "price_cut"
    tpr = "tpr"
    shipper = "shipper"
    end_cap = "end_cap"


class ElasticityMode(Enum):
    fallback = "fallback"
    utility_based = "utility_based"
    precomputed = "precomputed"


class ElasticityParams(CamelCaseModel):
    min_obs: Annotated[int, Field(title="Min Obs")] = 5
    elasticity_bounds: Annotated[
        tuple[float, float], Field(title="Elasticity Bounds")
    ] = [-5.0, 0.0]
    mape_threshold: Annotated[float, Field(title="Mape Threshold")] = 30.0


class ElasticityRequest(CamelCaseModel):
    retailer: Annotated[str | None, Field(title="Retailer")] = None
    category: Annotated[str | None, Field(title="Category")] = None
    subcategory: Annotated[str | None, Field(title="Subcategory")] = None
    sku_ids: Annotated[list[str] | None, Field(title="Sku Ids")] = None
    include_excluded: Annotated[bool, Field(title="Include Excluded")] = False
    params: ElasticityParams | None = None


class ElasticityResult(CamelCaseModel):
    retailer: Annotated[str, Field(title="Retailer")]
    sku_id: Annotated[str, Field(title="Sku Id")]
    elasticity: Annotated[float, Field(title="Elasticity")]
    r_squared: Annotated[float | None, Field(title="R Squared")] = None
    mape: Annotated[float | None, Field(title="Mape")] = None
    n_obs: Annotated[int, Field(title="N Obs")]
    intercept: Annotated[float | None, Field(title="Intercept")] = None
    include_flag: Annotated[bool, Field(title="Include Flag")]
    exclusion_reason: Annotated[str | None, Field(title="Exclusion Reason")] = None
    scenario_planning_ready: Annotated[bool, Field(title="Scenario Planning Ready")] = (
        False
    )
    promotion_features_used: Annotated[
        str | None, Field(title="Promotion Features Used")
    ] = None
    bucket_effects: Annotated[
        dict[str, BucketEffect] | None, Field(title="Bucket Effects")
    ] = None
    typical_promo_lift_pct: Annotated[
        float | None, Field(title="Typical Promo Lift Pct")
    ] = None


class ElasticitySummary(CamelCaseModel):
    total_models: Annotated[int, Field(title="Total Models")]
    included_models: Annotated[int, Field(title="Included Models")]
    excluded_models: Annotated[int, Field(title="Excluded Models")]
    avg_elasticity: Annotated[float | None, Field(title="Avg Elasticity")] = None
    scenario_ready_count: Annotated[int, Field(title="Scenario Ready Count")] = 0


class EntityType(Enum):
    customer = "customer"
    product = "product"
    category = "category"


class EventScatterItem(CamelCaseModel):
    event_id: Annotated[int, Field(title="Event Id")]
    brand: Annotated[str, Field(title="Brand")]
    legend_value: Annotated[str, Field(title="Legend Value")]
    roi: Annotated[float | None, Field(title="Roi")]
    depth_of_discount: Annotated[float | None, Field(title="Depth Of Discount")]
    volume: Annotated[float | None, Field(title="Volume")]
    promo_sales: Annotated[float | None, Field(title="Promo Sales")]
    pct_sales_on_promo: Annotated[float | None, Field(title="Pct Sales On Promo")]
    period: Annotated[str, Field(title="Period")]


class EventScatterResponse(CamelCaseModel):
    data: Annotated[list[EventScatterItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class FairShareItem(CamelCaseModel):
    brand: Annotated[str, Field(title="Brand")]
    market_share_pct: Annotated[float, Field(title="Market Share Pct")]
    promo_investment_share_pct: Annotated[
        float, Field(title="Promo Investment Share Pct")
    ]
    total_sales: Annotated[float, Field(title="Total Sales")]
    total_investment: Annotated[float, Field(title="Total Investment")]
    over_invested: Annotated[
        bool, Field(description="Above diagonal = over-invested", title="Over Invested")
    ]


class FairShareResponse(CamelCaseModel):
    data: Annotated[list[FairShareItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class FilterMetadata(CamelCaseModel):
    tenant_id: Annotated[int, Field(title="Tenant Id")]
    last_updated: Annotated[AwareDatetime, Field(title="Last Updated")]
    data_range: DataRange


class GroupBy(Enum):
    product = "product"
    category = "category"
    region = "region"
    customer = "customer"
    segment = "segment"


class HealthResponse(CamelCaseModel):
    status: Annotated[str, Field(title="Status")]
    timestamp: Annotated[AwareDatetime, Field(title="Timestamp")]
    service: Annotated[str, Field(title="Service")]
    version: Annotated[str, Field(title="Version")]


class HeatmapAxis(Enum):
    brand = "brand"
    sku = "sku"
    retailer = "retailer"
    category = "category"
    subcategory = "subcategory"
    depth_decile = "depth_decile"
    duration = "duration"
    time_since_last = "time_since_last"


class HeatmapCell(CamelCaseModel):
    x_value: Annotated[str, Field(title="X Value")]
    y_value: Annotated[str, Field(title="Y Value")]
    roi_pct: Annotated[float | None, Field(title="Roi Pct")]
    uplift_pct: Annotated[float | None, Field(title="Uplift Pct")]
    investment: Annotated[float | None, Field(title="Investment")]
    period: Annotated[str, Field(title="Period")]


class HeatmapResponse(CamelCaseModel):
    data: Annotated[list[HeatmapCell], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]
    x_axis: Annotated[str, Field(title="X Axis")]
    y_axis: Annotated[str, Field(title="Y Axis")]


class HistoricalPromoStats(CamelCaseModel):
    total_events: Annotated[int, Field(title="Total Events")]
    avg_roi: Annotated[float | None, Field(title="Avg Roi")]
    avg_uplift_pct: Annotated[float | None, Field(title="Avg Uplift Pct")]
    avg_depth: Annotated[float | None, Field(title="Avg Depth")]
    avg_duration_weeks: Annotated[float | None, Field(title="Avg Duration Weeks")]
    best_performing_depth: Annotated[str | None, Field(title="Best Performing Depth")]
    best_roi_by_depth: Annotated[float | None, Field(title="Best Roi By Depth")]


class IntensityItem(CamelCaseModel):
    group_value: Annotated[str, Field(title="Group Value")]
    pct_weeks_on_promo: Annotated[float, Field(title="Pct Weeks On Promo")]
    pct_sales_on_promo: Annotated[float, Field(title="Pct Sales On Promo")]
    share_pct: Annotated[float, Field(title="Share Pct")]


class IntensityResponse(CamelCaseModel):
    data: Annotated[list[IntensityItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class InvestmentDriverItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    driver_type: Annotated[str, Field(title="Driver Type")]
    total_investment: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Total Investment"),
    ]
    total_return: Annotated[
        str,
        Field(
            description="Incremental revenue or GP",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Total Return",
        ),
    ]
    roi_pct: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Roi Pct")
    ]
    event_count: Annotated[int, Field(title="Event Count")]
    avg_investment_per_event: Annotated[
        str,
        Field(
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Avg Investment Per Event",
        ),
    ]
    correlation_score: Annotated[
        str,
        Field(
            description="-1 to 1",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Correlation Score",
        ),
    ]


class InvestmentDriverRequest(CamelCaseModel):
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    customer_ids: Annotated[list[str] | None, Field(title="Customer Ids")] = None
    brands: Annotated[list[str] | None, Field(title="Brands")] = None
    driver_types: Annotated[list[DriverType] | None, Field(title="Driver Types")] = None


class InvestmentDriverResponse(CamelCaseModel):
    drivers: Annotated[list[InvestmentDriverItem], Field(title="Drivers")]
    top_driver: Annotated[str, Field(title="Top Driver")]
    worst_driver: Annotated[str, Field(title="Worst Driver")]
    summary: Annotated[dict[str, Summary | int], Field(title="Summary")]
    filters_applied: InvestmentDriverRequest


class KPIs(CamelCaseModel):
    volume_delta: Annotated[float, Field(title="Volume Delta")]
    sales_delta: Annotated[float, Field(title="Sales Delta")]
    margin_delta: Annotated[float, Field(title="Margin Delta")]
    items_changed: Annotated[int, Field(title="Items Changed")]
    total_items: Annotated[int, Field(title="Total Items")]
    changed_skus: Annotated[
        list[dict[str, Any]] | None, Field(title="Changed Skus")
    ] = None


class LandscapeChart(CamelCaseModel):
    title: Annotated[str, Field(title="Title")]
    chart_type: ChartType
    x: Annotated[str, Field(title="X")]
    y: Annotated[str, Field(title="Y")]
    series: Annotated[str | None, Field(title="Series")] = None
    y_axis_title: Annotated[str | None, Field(title="Y Axis Title")] = None
    data: Annotated[list[dict[str, Any]], Field(title="Data")]


class LandscapeLegend(Enum):
    brand = "brand"
    subcategory = "subcategory"
    category = "category"
    sku = "sku"
    manufacturer = "manufacturer"
    retailer = "retailer"
    channel = "channel"
    pack_size = "pack_size"
    price_tier = "price_tier"


class MarginContributionItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    customer_id: Annotated[str, Field(title="Customer Id")]
    customer_name: Annotated[str, Field(title="Customer Name")]
    segment: Annotated[str, Field(title="Segment")]
    revenue: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Revenue")
    ]
    cogs: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Cogs")
    ]
    trade_spend: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Trade Spend")
    ]
    gross_profit: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Gross Profit")
    ]
    margin_pct: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Margin Pct")
    ]
    contribution_pct: Annotated[
        str,
        Field(
            description="% of total portfolio margin",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Contribution Pct",
        ),
    ]
    rank: Annotated[int, Field(title="Rank")]
    is_negative: Annotated[bool, Field(title="Is Negative")]


class MarginContributionRequest(CamelCaseModel):
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    customer_segments: Annotated[list[str] | None, Field(title="Customer Segments")] = (
        None
    )
    brands: Annotated[list[str] | None, Field(title="Brands")] = None
    limit: Annotated[int, Field(title="Limit")] = 100


class MarginContributionResponse(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    data: Annotated[list[MarginContributionItem], Field(title="Data")]
    negative_margin_customers: Annotated[int, Field(title="Negative Margin Customers")]
    negative_margin_total: Annotated[
        str,
        Field(
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Negative Margin Total"
        ),
    ]
    summary: Annotated[dict[str, Summary | int], Field(title="Summary")]
    filters_applied: MarginContributionRequest


class MarketTrend(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    period: Annotated[str, Field(title="Period")]
    price_index: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Price Index")
    ]


class NPIProduct(CamelCaseModel):
    sku_id: Annotated[str, Field(title="Sku Id")]
    brand: Annotated[str, Field(title="Brand")]
    price: Annotated[float, Field(title="Price")]
    cost: Annotated[float | None, Field(title="Cost")] = None
    attributes: Annotated[list[dict[str, str]] | None, Field(title="Attributes")] = None


class OutlierMethod(Enum):
    zscore = "zscore"
    iqr = "iqr"
    percent = "percent"


class OutlierSummary(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    total_outliers: Annotated[int, Field(title="Total Outliers")]
    by_type: Annotated[dict[str, int], Field(title="By Type")]
    by_severity: Annotated[dict[str, int], Field(title="By Severity")]
    total_value_impact: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Total Value Impact"),
    ]


class OutlierType(Enum):
    high = "high"
    low = "low"
    pattern = "pattern"


class PackSizeFilter(CamelCaseModel):
    ranges: Annotated[list[str] | None, Field(title="Ranges")] = None
    uom: Annotated[str | None, Field(title="Uom")] = None


class Period(Enum):
    L52 = "L52"
    T52 = "T52"


class PeriodMetrics(CamelCaseModel):
    total_volume: Annotated[float, Field(title="Total Volume")] = 0
    total_baseline: Annotated[float, Field(title="Total Baseline")] = 0
    total_uplift: Annotated[float, Field(title="Total Uplift")] = 0
    total_investment: Annotated[float, Field(title="Total Investment")] = 0
    total_incremental_gp: Annotated[float, Field(title="Total Incremental Gp")] = 0
    avg_roi: Annotated[float | None, Field(title="Avg Roi")] = None
    pct_weeks_on_promo: Annotated[float, Field(title="Pct Weeks On Promo")] = 0


class PlannerRecommendation(CamelCaseModel):
    recommended_depth: Annotated[str, Field(title="Recommended Depth")]
    expected_roi: Annotated[float | None, Field(title="Expected Roi")]
    expected_uplift_pct: Annotated[float | None, Field(title="Expected Uplift Pct")]
    recommended_duration_weeks: Annotated[
        int, Field(title="Recommended Duration Weeks")
    ]
    estimated_investment: Annotated[float | None, Field(title="Estimated Investment")]
    estimated_incremental_volume: Annotated[
        float | None, Field(title="Estimated Incremental Volume")
    ]
    confidence: Annotated[
        str,
        Field(description="low/medium/high based on data points", title="Confidence"),
    ]


class MarginThreshold(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Margin Threshold"),
    ]


class GrowthThreshold(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Growth Threshold"),
    ]


class PortfolioQuadrantRequest(CamelCaseModel):
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    entity_type: EntityType = EntityType.customer
    margin_threshold: Annotated[
        MarginThreshold | None, Field(title="Margin Threshold")
    ] = None
    growth_threshold: Annotated[
        GrowthThreshold | None, Field(title="Growth Threshold")
    ] = None


class PriceChange(CamelCaseModel):
    product_id: Annotated[int, Field(title="Product Id")]
    new_price: Annotated[float | None, Field(title="New Price")] = None
    delisted: Annotated[bool, Field(title="Delisted")] = False


class PriceSpreadItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    product_id: Annotated[str, Field(title="Product Id")]
    product_name: Annotated[str, Field(title="Product Name")]
    customer_count: Annotated[int, Field(title="Customer Count")]
    min_price: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Min Price")
    ]
    max_price: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Max Price")
    ]
    avg_price: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Avg Price")
    ]
    spread_pct: Annotated[
        str,
        Field(
            description="(max-min)/avg × 100",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Spread Pct",
        ),
    ]
    std_dev: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Std Dev")
    ]
    outlier_count: Annotated[int, Field(title="Outlier Count")]


class PriceSpreadRequest(CamelCaseModel):
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    group_by: GroupBy = GroupBy.product
    customer_segments: Annotated[list[str] | None, Field(title="Customer Segments")] = (
        None
    )
    product_ids: Annotated[list[str] | None, Field(title="Product Ids")] = None
    categories: Annotated[list[str] | None, Field(title="Categories")] = None
    regions: Annotated[list[str] | None, Field(title="Regions")] = None


class PriceSpreadResponse(CamelCaseModel):
    data: Annotated[list[PriceSpreadItem], Field(title="Data")]
    customers_above_avg: Annotated[
        list[CustomerPriceVariance], Field(title="Customers Above Avg")
    ]
    customers_below_avg: Annotated[
        list[CustomerPriceVariance], Field(title="Customers Below Avg")
    ]
    summary: Annotated[dict[str, Summary | int], Field(title="Summary")]
    filters_applied: PriceSpreadRequest


class YoyChangePct(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Yoy Change Pct")
    ]


class QoqChangePct(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Qoq Change Pct")
    ]


class PricingEvolutionItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    customer_id: Annotated[str, Field(title="Customer Id")]
    customer_name: Annotated[str, Field(title="Customer Name")]
    period: Annotated[str, Field(title="Period")]
    avg_price: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Avg Price")
    ]
    price_index: Annotated[
        str,
        Field(
            description="Base=100",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Price Index",
        ),
    ]
    yoy_change_pct: Annotated[YoyChangePct | None, Field(title="Yoy Change Pct")] = None
    qoq_change_pct: Annotated[QoqChangePct | None, Field(title="Qoq Change Pct")] = None
    vs_market_avg_pct: Annotated[
        str,
        Field(
            description="+5 = 5% above market",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Vs Market Avg Pct",
        ),
    ]


class PricingEvolutionRequest(CamelCaseModel):
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    group_by: GroupBy = GroupBy.customer
    customer_ids: Annotated[list[str] | None, Field(title="Customer Ids")] = None
    product_ids: Annotated[list[str] | None, Field(title="Product Ids")] = None
    customer_segments: Annotated[list[str] | None, Field(title="Customer Segments")] = (
        None
    )
    period_type: Annotated[str, Field(title="Period Type")] = "quarter"


class PricingEvolutionResponse(CamelCaseModel):
    data: Annotated[list[PricingEvolutionItem], Field(title="Data")]
    market_avg_trend: Annotated[list[MarketTrend], Field(title="Market Avg Trend")]
    summary: Annotated[dict[str, Summary | int], Field(title="Summary")]
    filters_applied: PricingEvolutionRequest


class ProductEventItem(CamelCaseModel):
    event_id: Annotated[int, Field(title="Event Id")]
    start: Annotated[str, Field(title="Start")]
    end: Annotated[str, Field(title="End")]
    roi: Annotated[float | None, Field(title="Roi")]
    investment: Annotated[float, Field(title="Investment")]
    uplift: Annotated[float, Field(title="Uplift")]
    depth: Annotated[float | None, Field(title="Depth")]
    duration_weeks: Annotated[int | None, Field(title="Duration Weeks")] = None
    tactic: Annotated[str | None, Field(title="Tactic")] = None


class ProfitPoolItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    segment_type: Annotated[str, Field(title="Segment Type")]
    segment_value: Annotated[str, Field(title="Segment Value")]
    revenue: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Revenue")
    ]
    margin_dollars: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Margin Dollars")
    ]
    margin_pct: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Margin Pct")
    ]
    revenue_share_pct: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Revenue Share Pct"),
    ]
    margin_share_pct: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Margin Share Pct"),
    ]
    index: Annotated[
        str,
        Field(
            description="margin_share/revenue_share, >1 = over-indexed",
            pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
            title="Index",
        ),
    ]


class PromoEvent(CamelCaseModel):
    event_id: Annotated[int, Field(title="Event Id")]
    sku_id: Annotated[str, Field(title="Sku Id")]
    brand: Annotated[str, Field(title="Brand")]
    retailer: Annotated[str, Field(title="Retailer")]
    start_date: Annotated[date, Field(title="Start Date")]
    end_date: Annotated[date, Field(title="End Date")]
    duration_weeks: Annotated[int, Field(title="Duration Weeks")]
    roi: Annotated[float | None, Field(title="Roi")]
    uplift_pct: Annotated[float | None, Field(title="Uplift Pct")]
    depth_of_discount: Annotated[float | None, Field(title="Depth Of Discount")]
    promo_investment: Annotated[float | None, Field(title="Promo Investment")]


class PromoInvestmentItem(CamelCaseModel):
    period: Annotated[str, Field(title="Period")]
    group_value: Annotated[str, Field(title="Group Value")]
    promo_investment: Annotated[float, Field(title="Promo Investment")]
    share_pct: Annotated[float, Field(title="Share Pct")]
    promo_weeks: Annotated[int, Field(title="Promo Weeks")]


class PromoInvestmentResponse(CamelCaseModel):
    data: Annotated[list[PromoInvestmentItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class PromoPlannerResponse(CamelCaseModel):
    sku_id: Annotated[str, Field(title="Sku Id")]
    brand: Annotated[str, Field(title="Brand")]
    baseline: BaselineMetrics
    historical: HistoricalPromoStats
    depth_performance: Annotated[
        list[DepthRecommendation], Field(title="Depth Performance")
    ]
    recommendation: PlannerRecommendation


class Quadrant(Enum):
    star = "star"
    cash_cow = "cash_cow"
    question_mark = "question_mark"
    dog = "dog"


class RelatedFiltersRequest(CamelCaseModel):
    super_category: Annotated[str | None, Field(title="Super Category")] = None
    categories: Annotated[list[str] | None, Field(title="Categories")] = None
    subcategories: Annotated[list[str] | None, Field(title="Subcategories")] = None
    brands: Annotated[list[str] | None, Field(title="Brands")] = None
    retailers: Annotated[list[str] | None, Field(title="Retailers")] = None
    channels: Annotated[list[str] | None, Field(title="Channels")] = None
    price_tiers: Annotated[list[str] | None, Field(title="Price Tiers")] = None
    pack_size_range_values: Annotated[
        list[str] | None, Field(title="Pack Size Range Values")
    ] = None


class SKUResult(CamelCaseModel):
    product_id: Annotated[int, Field(title="Product Id")]
    sku_id: Annotated[str, Field(title="Sku Id")]
    upc: Annotated[str | None, Field(title="Upc")] = None
    retailer: Annotated[str, Field(title="Retailer")]
    brand: Annotated[str | None, Field(title="Brand")] = None
    old_price: Annotated[float, Field(title="Old Price")]
    new_price: Annotated[float | None, Field(title="New Price")] = None
    base_volume: Annotated[float, Field(title="Base Volume")]
    new_volume: Annotated[float, Field(title="New Volume")]
    volume_change_pct: Annotated[float, Field(title="Volume Change Pct")] = 0.0
    base_sales: Annotated[float, Field(title="Base Sales")]
    new_sales: Annotated[float, Field(title="New Sales")]
    sales_change_pct: Annotated[float, Field(title="Sales Change Pct")] = 0.0
    margin: Annotated[float, Field(title="Margin")]
    market_share_pct: Annotated[float, Field(title="Market Share Pct")]
    elasticity_used: Annotated[float, Field(title="Elasticity Used")]
    is_owned: Annotated[bool, Field(title="Is Owned")] = False
    is_delisted: Annotated[bool, Field(title="Is Delisted")] = False


class ScatterLegend(Enum):
    brand = "brand"
    sku = "sku"
    retailer = "retailer"
    depth_decile = "depth_decile"
    duration = "duration"
    time_since_last = "time_since_last"


class ScenarioStatus(Enum):
    draft = "draft"
    saved = "saved"
    archived = "archived"


class ScenarioSummary(CamelCaseModel):
    scenario_id: Annotated[int, Field(title="Scenario Id")]
    scenario_name: Annotated[str, Field(title="Scenario Name")]
    status: ScenarioStatus
    kpis: Annotated[dict[str, Any] | None, Field(title="Kpis")] = None
    created_at: Annotated[AwareDatetime, Field(title="Created At")]


class SeedResponse(CamelCaseModel):
    results: Annotated[dict[str, bool], Field(title="Results")]


class SegmentType(Enum):
    customer_tier = "customer_tier"
    channel = "channel"
    category = "category"
    region = "region"


class Severity(Enum):
    warning = "warning"
    critical = "critical"


class SplitBy(Enum):
    brand = "brand"
    retailer = "retailer"
    subcategory = "subcategory"
    product = "product"


class TacticGroup(CamelCaseModel):
    group_value: Annotated[str, Field(title="Group Value")]
    total_volume: Annotated[float, Field(title="Total Volume")] = 0
    baseline_volume: Annotated[float, Field(title="Baseline Volume")] = 0
    incremental_volume: Annotated[float, Field(title="Incremental Volume")] = 0
    uplift_pct: Annotated[float | None, Field(title="Uplift Pct")] = None
    total_investment: Annotated[float, Field(title="Total Investment")] = 0
    total_incremental_gp: Annotated[float, Field(title="Total Incremental Gp")] = 0
    roi_pct: Annotated[float | None, Field(title="Roi Pct")] = None
    event_count: Annotated[int, Field(title="Event Count")] = 0


class TacticGroupBy(Enum):
    depth_decile = "depth_decile"
    duration = "duration"
    time_since_last = "time_since_last"


class TacticItem(CamelCaseModel):
    tactic: Annotated[str, Field(title="Tactic")]
    group_value: Annotated[str, Field(title="Group Value")]
    investment: Annotated[float, Field(title="Investment")]
    uplift: Annotated[float, Field(title="Uplift")]
    roi: Annotated[float | None, Field(title="Roi")]
    incremental_gp: Annotated[float, Field(title="Incremental Gp")]
    period: Period
    growth_pct: Annotated[float | None, Field(title="Growth Pct")] = None


class TacticXAxis(Enum):
    promo_tactic = "promo_tactic"
    depth_decile = "depth_decile"
    duration = "duration"
    time_since_last = "time_since_last"


class TradeGroupBy(Enum):
    customer = "customer"
    channel = "channel"
    product = "product"
    period = "period"


class TransparencyItem(CamelCaseModel):
    group_value: Annotated[str, Field(title="Group Value")]
    period: Annotated[Period, Field(description="L52 (Trailing 12) or T52 (Prior 12)")]
    promo_investment: Annotated[float, Field(title="Promo Investment")]
    pct_volume_on_promo: Annotated[
        float, Field(description="% of Sales on Promo", title="Pct Volume On Promo")
    ]
    pct_weeks_on_promo: Annotated[
        float, Field(description="% of Weeks on Promo", title="Pct Weeks On Promo")
    ]
    pct_depth_of_discount: Annotated[
        float, Field(description="Depth of Discount %", title="Pct Depth Of Discount")
    ]
    avg_duration: Annotated[
        float,
        Field(description="Avg Promo Event Duration (weeks)", title="Avg Duration"),
    ]
    growth_pct: Annotated[float | None, Field(title="Growth Pct")] = None


class TransparencySummary(CamelCaseModel):
    periods: Annotated[list[Period], Field(title="Periods")] = [Period.L52, Period.T52]
    total_investment_l52: Annotated[float, Field(title="Total Investment L52")]
    total_investment_t52: Annotated[float, Field(title="Total Investment T52")]


class UserInfoResponse(CamelCaseModel):
    sub: Annotated[str, Field(title="Sub")]
    email: Annotated[str | None, Field(title="Email")]
    groups: Annotated[list[str], Field(title="Groups")]


class VTMMode(Enum):
    market_share = "market_share"
    aggregated_utilities = "aggregated_utilities"
    utility_blend = "utility_blend"


class ValidationError(CamelCaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class WaterfallData(CamelCaseModel):
    lost_skus: Annotated[list[dict[str, Any]] | None, Field(title="Lost Skus")] = None
    gained_skus: Annotated[list[dict[str, Any]] | None, Field(title="Gained Skus")] = (
        None
    )
    lost_sku_id: Annotated[str | None, Field(title="Lost Sku Id")] = None
    lost_volume: Annotated[float, Field(title="Lost Volume")] = 0.0
    lost_sales: Annotated[float, Field(title="Lost Sales")] = 0.0


class WaterfallStep(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    step_name: Annotated[
        str, Field(description="gross_revenue, off_invoice, etc.", title="Step Name")
    ]
    step_order: Annotated[int, Field(title="Step Order")]
    amount: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Amount")
    ]
    pct_of_gross: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Pct Of Gross")
    ]
    cumulative_pct: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Cumulative Pct")
    ]


class WeeklyBaseline(CamelCaseModel):
    week: Annotated[date, Field(title="Week")]
    is_promo: Annotated[bool, Field(title="Is Promo")]
    volume: Annotated[float, Field(title="Volume")]
    baseline_volume: Annotated[float, Field(title="Baseline Volume")]
    volume_uplift: Annotated[float, Field(title="Volume Uplift")]
    price: Annotated[float | None, Field(title="Price")] = None
    non_promo_price: Annotated[float | None, Field(title="Non Promo Price")] = None
    promo_investment: Annotated[float | None, Field(title="Promo Investment")] = None
    incremental_gp: Annotated[float | None, Field(title="Incremental Gp")] = None
    roi: Annotated[float | None, Field(title="Roi")] = None
    depth_of_discount: Annotated[float | None, Field(title="Depth Of Discount")] = None


class SkaixApiSchemasCategoryLandscapeSplitBy(Enum):
    brand = "brand"
    subcategory = "subcategory"
    category = "category"
    sku = "sku"
    manufacturer = "manufacturer"
    retailer = "retailer"
    channel = "channel"
    pack_size = "pack_size"


class SkaixApiSchemasCategoryPriceMetric(Enum):
    price_per_unit = "price_per_unit"
    price_per_scaled_volume = "price_per_scaled_volume"


class SkaixApiSchemasChannelLandscapeSplitBy(Enum):
    brand = "brand"
    subcategory = "subcategory"
    sku = "sku"


class SkaixApiSchemasFiltersPriceMetric(Enum):
    price_per_unit = "price_per_unit"
    price_per_volume = "price_per_volume"


class SkaixApiSchemasPricingBrandLadderItem(CamelCaseModel):
    brand: Annotated[str, Field(title="Brand")]
    avg_price: Annotated[
        float, Field(description="Average price (all)", title="Avg Price")
    ]
    promo_price: Annotated[
        float | None, Field(description="Average promo price", title="Promo Price")
    ] = None
    non_promo_price: Annotated[
        float | None,
        Field(description="Average non-promo price", title="Non Promo Price"),
    ] = None
    total_volume: Annotated[
        float, Field(description="Total units sold", title="Total Volume")
    ]
    promo_volume: Annotated[
        float | None, Field(description="Promo units sold", title="Promo Volume")
    ] = None
    non_promo_volume: Annotated[
        float | None,
        Field(description="Non-promo units sold", title="Non Promo Volume"),
    ] = None
    dollar_sales: Annotated[float, Field(title="Dollar Sales")]
    promo_sales: Annotated[
        float | None, Field(description="Promo dollar sales", title="Promo Sales")
    ] = None
    non_promo_sales: Annotated[
        float | None,
        Field(description="Non-promo dollar sales", title="Non Promo Sales"),
    ] = None
    share_pct: Annotated[float, Field(title="Share Pct")]


class SkaixApiSchemasPricingPricePackItem(CamelCaseModel):
    pack_size_range: Annotated[str, Field(title="Pack Size Range")]
    brand: Annotated[str, Field(title="Brand")]
    avg_price: Annotated[float, Field(title="Avg Price")]
    dollar_sales: Annotated[float, Field(title="Dollar Sales")]
    share_pct: Annotated[float, Field(title="Share Pct")]
    growth_pct: Annotated[float | None, Field(title="Growth Pct")] = None


class SkaixApiSchemasSimulatorBasePriceMetric(Enum):
    price_per_unit = "price_per_unit"
    price_per_volume = "price_per_volume"


class SkaixApiSchemasSimulatorChartsBrandLadderItem(CamelCaseModel):
    brand: Annotated[str, Field(title="Brand")]
    min_price: Annotated[float, Field(title="Min Price")]
    avg_price: Annotated[float, Field(title="Avg Price")]
    max_price: Annotated[float, Field(title="Max Price")]
    volume: Annotated[float, Field(title="Volume")]
    dollar_sales: Annotated[float, Field(title="Dollar Sales")]


class SkaixApiSchemasSimulatorChartsPricePackItem(CamelCaseModel):
    pack_size_range_value: Annotated[str, Field(title="Pack Size Range Value")]
    price: Annotated[float, Field(title="Price")]
    dollar_sales: Annotated[float, Field(title="Dollar Sales")]
    brand: Annotated[str, Field(title="Brand")]


class BaselineData(CamelCaseModel):
    sku_id: Annotated[str, Field(title="Sku Id")]
    sku_name: Annotated[str, Field(title="Sku Name")]
    retailer: Annotated[str, Field(title="Retailer")]
    brand: Annotated[str, Field(title="Brand")]
    p12: PeriodMetrics
    t12: PeriodMetrics
    weeks: Annotated[list[WeeklyBaseline], Field(title="Weeks")]


class BaselineReviewResponse(CamelCaseModel):
    data: BaselineData


class BrandLadderChart(CamelCaseModel):
    title: Annotated[str, Field(title="Title")] = "Price Ladder"
    data: Annotated[
        list[SkaixApiSchemasSimulatorChartsBrandLadderItem], Field(title="Data")
    ]
    group_by: Annotated[str, Field(title="Group By")] = "brand"
    x_axis_title: Annotated[str, Field(title="X Axis Title")] = "Brand"
    y_axis_title: Annotated[str, Field(title="Y Axis Title")] = "Price"


class BrandLadderResponse(CamelCaseModel):
    data: Annotated[list[SkaixApiSchemasPricingBrandLadderItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class CDTData(CamelCaseModel):
    tree: CDTNode
    nodes: Annotated[list[CDTNodeFlat], Field(title="Nodes")]
    attribute_ranks: Annotated[
        list[CDTAttrRank] | None, Field(title="Attribute Ranks")
    ] = None


class CDTResponse(CamelCaseModel):
    data: CDTData
    summary: CDTSummary


class CategoryFormatRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    start_date: Annotated[
        date | None, Field(description="Analysis period start", title="Start Date")
    ] = None
    end_date: Annotated[
        date | None, Field(description="Analysis period end", title="End Date")
    ] = None
    sku_ids: Annotated[
        list[str] | None, Field(description="Filter by SKU IDs", title="Sku Ids")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None
    price_metric: Annotated[
        SkaixApiSchemasCategoryPriceMetric,
        Field(description="Price calculation method"),
    ] = SkaixApiSchemasCategoryPriceMetric.price_per_unit


class CategoryLandscapeRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    start_date: Annotated[
        date | None, Field(description="Analysis period start", title="Start Date")
    ] = None
    end_date: Annotated[
        date | None, Field(description="Analysis period end", title="End Date")
    ] = None
    sku_ids: Annotated[
        list[str] | None, Field(description="Filter by SKU IDs", title="Sku Ids")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None
    price_metric: Annotated[
        SkaixApiSchemasCategoryPriceMetric,
        Field(description="Price calculation method"),
    ] = SkaixApiSchemasCategoryPriceMetric.price_per_unit
    split_by: Annotated[
        SkaixApiSchemasCategoryLandscapeSplitBy,
        Field(description="Primary grouping dimension"),
    ] = SkaixApiSchemasCategoryLandscapeSplitBy.brand
    legend: Annotated[
        LandscapeLegend | None,
        Field(description="Legend grouping variable for chart series"),
    ] = None


class CategoryPackSizeRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    start_date: Annotated[
        date | None, Field(description="Analysis period start", title="Start Date")
    ] = None
    end_date: Annotated[
        date | None, Field(description="Analysis period end", title="End Date")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None
    price_metric: Annotated[
        SkaixApiSchemasCategoryPriceMetric,
        Field(description="Price calculation method"),
    ] = SkaixApiSchemasCategoryPriceMetric.price_per_unit


class CategoryPriceTiersRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    start_date: Annotated[
        date | None, Field(description="Analysis period start", title="Start Date")
    ] = None
    end_date: Annotated[
        date | None, Field(description="Analysis period end", title="End Date")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None
    price_metric: Annotated[
        SkaixApiSchemasCategoryPriceMetric,
        Field(description="Price calculation method"),
    ] = SkaixApiSchemasCategoryPriceMetric.price_per_unit


class CategoryProductRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    start_date: Annotated[
        date | None, Field(description="Analysis period start", title="Start Date")
    ] = None
    end_date: Annotated[
        date | None, Field(description="Analysis period end", title="End Date")
    ] = None
    sku_ids: Annotated[
        list[str] | None, Field(description="Filter by SKU IDs", title="Sku Ids")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None
    price_metric: Annotated[
        SkaixApiSchemasCategoryPriceMetric,
        Field(description="Price calculation method"),
    ] = SkaixApiSchemasCategoryPriceMetric.price_per_unit
    limit: Annotated[
        int, Field(description="Max products to return", title="Limit")
    ] = 50


class CategorySeasonalityRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    start_date: Annotated[
        date | None, Field(description="Analysis period start", title="Start Date")
    ] = None
    end_date: Annotated[
        date | None, Field(description="Analysis period end", title="End Date")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None
    granularity: Annotated[
        str, Field(description="month or week", title="Granularity")
    ] = "month"
    split_by: SplitBy | None = None


class CategoryTrendsRequest(CamelCaseModel):
    super_category: Annotated[
        str | None, Field(description="Super category scope", title="Super Category")
    ] = None
    sku_ids: Annotated[
        list[str] | None, Field(description="Filter by SKU IDs", title="Sku Ids")
    ] = None
    brands: Annotated[
        list[str] | None, Field(description="Filter by brands", title="Brands")
    ] = None
    categories: Annotated[
        list[str] | None, Field(description="Filter by categories", title="Categories")
    ] = None
    subcategories: Annotated[
        list[str] | None,
        Field(description="Filter by subcategories", title="Subcategories"),
    ] = None
    retailers: Annotated[
        list[str] | None, Field(description="Filter by retailers", title="Retailers")
    ] = None
    channels: Annotated[
        list[str] | None, Field(description="Filter by channels", title="Channels")
    ] = None
    pack_size_range_values: Annotated[
        list[str] | None,
        Field(
            description="Filter by pack size range values",
            title="Pack Size Range Values",
        ),
    ] = None
    price_tiers: Annotated[
        list[str] | None,
        Field(description="Filter by price tiers", title="Price Tiers"),
    ] = None
    price_metric: Annotated[
        SkaixApiSchemasCategoryPriceMetric,
        Field(description="Price calculation method"),
    ] = SkaixApiSchemasCategoryPriceMetric.price_per_unit
    legend: Annotated[
        LandscapeLegend | None,
        Field(description="Legend grouping variable for chart series"),
    ] = None


class ChannelLandscapeRequest(CamelCaseModel):
    super_category: Annotated[str | None, Field(title="Super Category")] = None
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    brands: Annotated[list[str] | None, Field(title="Brands")] = None
    retailers: Annotated[list[str] | None, Field(title="Retailers")] = None
    categories: Annotated[list[str] | None, Field(title="Categories")] = None
    subcategories: Annotated[list[str] | None, Field(title="Subcategories")] = None
    channels: Annotated[list[str] | None, Field(title="Channels")] = None
    pack_size_range_values: Annotated[
        list[str] | None, Field(title="Pack Size Range Values")
    ] = None
    price_tiers: Annotated[list[str] | None, Field(title="Price Tiers")] = None
    sku_ids: Annotated[list[str] | None, Field(title="Sku Ids")] = None
    price_metric: SkaixApiSchemasFiltersPriceMetric = (
        SkaixApiSchemasFiltersPriceMetric.price_per_unit
    )
    split_by: SkaixApiSchemasChannelLandscapeSplitBy | None = (
        SkaixApiSchemasChannelLandscapeSplitBy.brand
    )
    client_brand: Annotated[
        str | None,
        Field(description="Brand for benchmark comparison", title="Client Brand"),
    ] = None
    legend: Annotated[
        ChannelLegend | None,
        Field(description="Legend grouping variable for chart series"),
    ] = None


class ChannelLandscapeResponse(CamelCaseModel):
    charts: Annotated[list[LandscapeChart], Field(title="Charts")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]
    filters_applied: ChannelLandscapeRequest | None = None


class ChartData(CamelCaseModel):
    title: Annotated[str, Field(title="Title")]
    chart_type: ChartType
    x: Annotated[str | None, Field(title="X")] = None
    y: Annotated[str | None, Field(title="Y")] = None
    series: Annotated[str | None, Field(title="Series")] = None
    y_axis_title: Annotated[str | None, Field(title="Y Axis Title")] = None
    data: Annotated[list[Any], Field(title="Data")]


class DepthQCItem(CamelCaseModel):
    decile: Annotated[str, Field(title="Decile")]
    event_count: Annotated[int, Field(title="Event Count")]
    avg_roi: Annotated[float | None, Field(title="Avg Roi")]
    avg_uplift: Annotated[float | None, Field(title="Avg Uplift")]
    investment: Annotated[float, Field(title="Investment")]
    period: Period
    growth_pct: Annotated[float | None, Field(title="Growth Pct")] = None


class DiscountDepthQCResponse(CamelCaseModel):
    data: Annotated[list[DepthQCItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class EffectivenessItem(CamelCaseModel):
    group_value: Annotated[str, Field(title="Group Value")]
    investment: Annotated[float, Field(title="Investment")]
    incremental_gp: Annotated[float, Field(title="Incremental Gp")]
    roi: Annotated[float | None, Field(title="Roi")]
    uplift: Annotated[float, Field(title="Uplift")]
    period: Period
    growth_pct: Annotated[float | None, Field(title="Growth Pct")] = None


class ElasticityData(CamelCaseModel):
    results: Annotated[list[ElasticityResult], Field(title="Results")]


class ElasticityResponse(CamelCaseModel):
    data: ElasticityData
    summary: ElasticitySummary


class FilterOptions(CamelCaseModel):
    super_categories: Annotated[list[str] | None, Field(title="Super Categories")] = (
        None
    )
    sku_ids: Annotated[list[str] | None, Field(title="Sku Ids")] = None
    brands: Annotated[list[str] | None, Field(title="Brands")] = None
    own_brands: Annotated[
        list[str] | None,
        Field(
            description="Brands owned by the client (from tenant config)",
            title="Own Brands",
        ),
    ] = None
    categories: Annotated[list[str] | None, Field(title="Categories")] = None
    subcategories: Annotated[list[str] | None, Field(title="Subcategories")] = None
    retailers: Annotated[list[str] | None, Field(title="Retailers")] = None
    channels: Annotated[list[str] | None, Field(title="Channels")] = None
    price_tiers: Annotated[list[str] | None, Field(title="Price Tiers")] = None
    pack_size_range_values: Annotated[
        list[str] | None, Field(title="Pack Size Range Values")
    ] = None
    pack_size: PackSizeFilter | None = None


class FilterValuesResponse(CamelCaseModel):
    filters: FilterOptions
    metadata: FilterMetadata


class GTNWaterfallItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    group_by_value: Annotated[str, Field(title="Group By Value")]
    gross_revenue: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Gross Revenue")
    ]
    net_revenue: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Net Revenue")
    ]
    total_leakage_pct: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Total Leakage Pct"),
    ]
    steps: Annotated[list[WaterfallStep], Field(title="Steps")]


class GTNWaterfallRequest(CamelCaseModel):
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    group_by: TradeGroupBy = TradeGroupBy.customer
    customer_ids: Annotated[list[str] | None, Field(title="Customer Ids")] = None
    channels: Annotated[list[str] | None, Field(title="Channels")] = None
    brands: Annotated[list[str] | None, Field(title="Brands")] = None


class GTNWaterfallResponse(CamelCaseModel):
    data: Annotated[list[GTNWaterfallItem], Field(title="Data")]
    benchmark: Annotated[GTNWaterfallItem, Field(description="Portfolio average")]
    summary: Annotated[dict[str, Summary | int], Field(title="Summary")]
    filters_applied: GTNWaterfallRequest


class HTTPValidationError(CamelCaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class MarketEffectivenessResponse(CamelCaseModel):
    data: Annotated[list[EffectivenessItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class PortfolioQuadrantItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    entity_type: Annotated[str, Field(title="Entity Type")]
    entity_id: Annotated[str, Field(title="Entity Id")]
    entity_name: Annotated[str, Field(title="Entity Name")]
    revenue: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Revenue")
    ]
    margin_pct: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Margin Pct")
    ]
    growth_pct: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Growth Pct")
    ]
    quadrant: Quadrant


class PortfolioQuadrantResponse(CamelCaseModel):
    data: Annotated[list[PortfolioQuadrantItem], Field(title="Data")]
    thresholds: Annotated[
        dict[str, str],
        Field(description="{margin_threshold, growth_threshold}", title="Thresholds"),
    ]
    quadrant_counts: Annotated[dict[str, int], Field(title="Quadrant Counts")]
    summary: Annotated[dict[str, Summary | int], Field(title="Summary")]
    filters_applied: PortfolioQuadrantRequest


class PriceOutlierItem(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    transaction_id: Annotated[str, Field(title="Transaction Id")]
    customer_id: Annotated[str, Field(title="Customer Id")]
    customer_name: Annotated[str, Field(title="Customer Name")]
    product_id: Annotated[str, Field(title="Product Id")]
    transaction_date: Annotated[date, Field(title="Transaction Date")]
    price: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Price")
    ]
    expected_price: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Expected Price")
    ]
    deviation_pct: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Deviation Pct")
    ]
    z_score: Annotated[
        str, Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Z Score")
    ]
    outlier_type: OutlierType
    severity: Severity


class PriceOutlierRequest(CamelCaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    detection_method: OutlierMethod = OutlierMethod.zscore
    zscore_threshold: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Zscore Threshold"),
    ] = "2.0"
    percent_threshold: Annotated[
        str,
        Field(pattern="^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$", title="Percent Threshold"),
    ] = "20.0"
    customer_ids: Annotated[list[str] | None, Field(title="Customer Ids")] = None
    product_ids: Annotated[list[str] | None, Field(title="Product Ids")] = None
    include_severity: Annotated[
        list[Severity] | None, Field(title="Include Severity")
    ] = None


class PriceOutlierResponse(CamelCaseModel):
    outliers: Annotated[list[PriceOutlierItem], Field(title="Outliers")]
    summary: OutlierSummary
    filters_applied: PriceOutlierRequest


class PricePackCurveChart(CamelCaseModel):
    title: Annotated[str, Field(title="Title")] = (
        "Price by Pack Size Range (Bubble = Sales)"
    )
    data: Annotated[
        list[SkaixApiSchemasSimulatorChartsPricePackItem], Field(title="Data")
    ]
    x_axis_title: Annotated[str, Field(title="X Axis Title")] = "Pack Size Range (oz)"
    y_axis_title: Annotated[str, Field(title="Y Axis Title")] = (
        "Average price by Pack Size"
    )
    size_field: Annotated[str, Field(title="Size Field")] = "dollar_sales"
    series_field: Annotated[str, Field(title="Series Field")] = "brand"


class PricePackResponse(CamelCaseModel):
    data: Annotated[list[SkaixApiSchemasPricingPricePackItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class ProductDeepDiveResponse(CamelCaseModel):
    sku_id: Annotated[str, Field(title="Sku Id")]
    sku_name: Annotated[str | None, Field(title="Sku Name")] = None
    retailer: Annotated[str | None, Field(title="Retailer")] = None
    brand: Annotated[str, Field(title="Brand")]
    total_events: Annotated[int, Field(title="Total Events")]
    avg_roi: Annotated[float | None, Field(title="Avg Roi")]
    avg_uplift: Annotated[float | None, Field(title="Avg Uplift")]
    total_investment: Annotated[float, Field(title="Total Investment")]
    avg_depth: Annotated[float | None, Field(title="Avg Depth")]
    avg_duration_weeks: Annotated[float | None, Field(title="Avg Duration Weeks")] = (
        None
    )
    events: Annotated[list[ProductEventItem], Field(title="Events")]


class ProfitPoolRequest(CamelCaseModel):
    start_date: Annotated[date | None, Field(title="Start Date")] = None
    end_date: Annotated[date | None, Field(title="End Date")] = None
    segment_type: SegmentType = SegmentType.customer_tier
    segments: Annotated[list[str] | None, Field(title="Segments")] = None


class ProfitPoolResponse(CamelCaseModel):
    data: Annotated[list[ProfitPoolItem], Field(title="Data")]
    pareto: Annotated[
        dict[str, str],
        Field(description="{top_20_pct_revenue, top_20_pct_margin}", title="Pareto"),
    ]
    summary: Annotated[dict[str, Summary | int], Field(title="Summary")]
    filters_applied: ProfitPoolRequest


class PromoCalendarResponse(CamelCaseModel):
    data: Annotated[list[PromoEvent], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class ScenarioListResponse(CamelCaseModel):
    scenarios: Annotated[list[ScenarioSummary], Field(title="Scenarios")]
    total: Annotated[int, Field(title="Total")]


class SimulationConfig(CamelCaseModel):
    elasticity_mode: ElasticityMode = ElasticityMode.fallback
    fallback_elasticity: Annotated[float, Field(title="Fallback Elasticity")] = -1.2
    vtm_mode: VTMMode = VTMMode.market_share
    vtm_blend: Annotated[float, Field(ge=0.0, le=1.0, title="Vtm Blend")] = 0.9
    use_vw: Annotated[bool, Field(title="Use Vw")] = False
    vw_sensitivity: Annotated[float, Field(ge=0.0, le=5.0, title="Vw Sensitivity")] = (
        1.5
    )
    price_metric: SkaixApiSchemasSimulatorBasePriceMetric = (
        SkaixApiSchemasSimulatorBasePriceMetric.price_per_unit
    )


class SimulatorCharts(CamelCaseModel):
    brand_ladder: BrandLadderChart | None = None
    price_pack_curve: PricePackCurveChart | None = None


class SimulatorRunRequest(CamelCaseModel):
    price_changes: Annotated[list[PriceChange], Field(title="Price Changes")]
    npi_products: Annotated[list[NPIProduct] | None, Field(title="Npi Products")] = None
    owned_brand: Annotated[str | None, Field(title="Owned Brand")] = None
    config: SimulationConfig | None = None
    include_charts: Annotated[bool, Field(title="Include Charts")] = False


class SimulatorRunResponse(CamelCaseModel):
    data: Annotated[list[SKUResult], Field(title="Data")]
    kpis: KPIs
    waterfall: WaterfallData
    charts: SimulatorCharts | None = None


class TacticData(CamelCaseModel):
    sku_id: Annotated[str, Field(title="Sku Id")]
    retailer: Annotated[str, Field(title="Retailer")]
    group_by: Annotated[str, Field(title="Group By")]
    p12: Annotated[list[TacticGroup], Field(title="P12")]
    t12: Annotated[list[TacticGroup], Field(title="T12")]


class TacticEffectivenessResponse(CamelCaseModel):
    data: Annotated[list[TacticItem], Field(title="Data")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class TransparencyResponse(CamelCaseModel):
    data: Annotated[list[TransparencyItem], Field(title="Data")]
    summary: TransparencySummary


class CategoryFormatResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Summary | int], Field(description="Summary metrics", title="Summary")
    ]
    filters_applied: CategoryFormatRequest


class CategoryInnovationResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Summary | int], Field(description="Summary metrics", title="Summary")
    ]
    filters_applied: CategoryInnovationRequest


class CategoryLandscapeResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Any], Field(description="Summary metrics", title="Summary")
    ]
    filters_applied: CategoryLandscapeRequest


class CategoryPackSizeResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Any], Field(description="Summary metrics", title="Summary")
    ]
    filters_applied: CategoryPackSizeRequest


class CategoryPriceTiersResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Any], Field(description="Summary metrics", title="Summary")
    ]
    filters_applied: CategoryPriceTiersRequest


class CategoryProductResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Any], Field(description="Summary metrics", title="Summary")
    ]
    filters_applied: CategoryProductRequest
    coverage: Annotated[
        dict[str, Any] | None,
        Field(description="Data coverage metadata", title="Coverage"),
    ] = None


class CategorySeasonalityResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Summary | int], Field(description="Summary metrics", title="Summary")
    ]
    filters_applied: CategorySeasonalityRequest


class CategoryTrendsResponse(CamelCaseModel):
    charts: Annotated[list[ChartData], Field(title="Charts")]
    summary: Annotated[
        dict[str, Summary | int | str],
        Field(description="Summary metrics", title="Summary"),
    ]
    filters_applied: CategoryTrendsRequest


class DeepDiveTacticResponse(CamelCaseModel):
    data: TacticData


class ScenarioCreate(CamelCaseModel):
    scenario_name: Annotated[str, Field(title="Scenario Name")]
    description: Annotated[str | None, Field(title="Description")] = None
    config: SimulationConfig | None = None
    price_changes: Annotated[list[dict[str, Any]], Field(title="Price Changes")]
    results: Annotated[list[dict[str, Any]] | None, Field(title="Results")] = None
    kpis: Annotated[dict[str, Any] | None, Field(title="Kpis")] = None
    waterfall_data: Annotated[dict[str, Any] | None, Field(title="Waterfall Data")] = (
        None
    )


class ScenarioDetail(CamelCaseModel):
    scenario_id: Annotated[int, Field(title="Scenario Id")]
    scenario_name: Annotated[str, Field(title="Scenario Name")]
    description: Annotated[str | None, Field(title="Description")] = None
    status: ScenarioStatus
    config: SimulationConfig | None = None
    price_changes: Annotated[list[dict[str, Any]], Field(title="Price Changes")]
    base_snapshot: Annotated[dict[str, Any] | None, Field(title="Base Snapshot")] = None
    results: Annotated[list[dict[str, Any]] | None, Field(title="Results")] = None
    kpis: Annotated[dict[str, Any] | None, Field(title="Kpis")] = None
    waterfall_data: Annotated[dict[str, Any] | None, Field(title="Waterfall Data")] = (
        None
    )
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class ScenarioUpdate(CamelCaseModel):
    scenario_name: Annotated[str | None, Field(title="Scenario Name")] = None
    description: Annotated[str | None, Field(title="Description")] = None
    status: Annotated[str | None, Field(title="Status")] = None
    config: SimulationConfig | None = None
    price_changes: Annotated[
        list[dict[str, Any]] | None, Field(title="Price Changes")
    ] = None
    results: Annotated[list[dict[str, Any]] | None, Field(title="Results")] = None
    kpis: Annotated[dict[str, Any] | None, Field(title="Kpis")] = None
    waterfall_data: Annotated[dict[str, Any] | None, Field(title="Waterfall Data")] = (
        None
    )


CDTNode.model_rebuild()
